# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Gemfile                                            :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: atropnik <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/03/15 21:40:19 by atropnik          #+#    #+#              #
#    Updated: 2019/03/15 21:40:27 by atropnik         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# frozen_string_literal: true
source "https://rubygems.org"

gem 'oauth2'
gem 'multi_json'
gem 'activesupport', '~> 4.2', '>= 4.2.7.1'
gem 'oj'
gem 'rack', '~> 1.6', '>= 1.6.4'
